### ISSUE TITLE
Constructor cannot be called twice.

### ISSUE THREAD

**Issue by VadimPushtaev** [hirose31/p5-InfluxDB#5]
```perl
use InfluxDB;
InfluxDB->new(host => '192.168.0.93', port => 8086, username => 'root', password => 'root', database => 'test');
InfluxDB->new(host => '192.168.0.93', port => 8086, username => 'root', password => 'root', database => 'test');
```

This code throws `Odd number of parameters to new() at /usr/local/share/perl/5.14.2/Data/Validator.pm line 123`.

I believe that's because of `state $rule = Data::Validator->new(...)` in the constructor.

**Comment by hirose31** [comment]
Thanks for your bug reporting! I've just released v1.003, You will available soon.
